### ISSUE TITLE
Benchmarker (score collector)

### ISSUE THREAD

**Issue by Willian-Zhang** [starcraft2-ai/rl-battle#26]
- [x] #29
- [x] **Should** be able to run though multiple Agents
- [x] **Should** have FLAGs for setting configuration and correspondent default value
- [x] **Should** be multithread compatiple

**Comment by Willian-Zhang** [comment]
@jimmyahacker @ZhuRoy007 did any of you check if `Should be able to run though multiple Agents` works?
specially the AtariAgent?

**Comment by jimmyahacker** [comment]
I tried. All worked
