### ISSUE TITLE
Score environment

### ISSUE THREAD

**Issue by ZhuRoy007** [starcraft2-ai/rl-battle#29]

**Comment by Willian-Zhang** [comment]
Consider change previous score collect function to `benchmark.py`

**Comment by ZhuRoy007** [comment]
is it necessary to change function to a separate file?

**Comment by Willian-Zhang** [comment]
Check if it works with multiple threads

**Comment by ZhuRoy007** [comment]
multiple threads not supported, have multiple result, Help needed
